import { NextUiProvider } from "../providers";

import "@/app/globals.css";
import SideBarArtist from "./SideBarArtist";
import { Toaster } from "sonner";
import { AuthProvider } from "../context/AuthContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextUiProvider>
          <AuthProvider>
            <Toaster />
            <div className="flex h-screen w-full overflow-hidden">
              <SideBarArtist />

              <div className="flex-1 flex flex-col overflow-y-scroll">
                {children}
              </div>
            </div>
          </AuthProvider>
        </NextUiProvider>
      </body>
    </html>
  );
}
