import "@/app/globals.css";
import { NextUiProvider } from "../providers";
import { Toaster } from "sonner";
import { AuthProvider } from "../context/AuthContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="dark text-foreground bg-background p-3">
          <NextUiProvider>
            <Toaster />
            <header className="flex justify-between mb-3 absolute">
              <img src="/spotify.png" className="h-20 w-20" alt="" srcset="" />
            </header>
            <main className="">{children}</main>
          </NextUiProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
